### ISSUE TITLE
Add methods commonly used for `lm`-class objects

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#26]
# TO-DO
- [x] `add1()`: Intercept it (346f84a76dd80ee352830a8fdfca2f26aac09329)
- [x] `vcov()`. (0363efba153e65cc008495abb961172d550da2d3)
- [x] `confint()`. (2877f1dc01224d7244d54b6536c3c0a31d79994f)
- [x] `update()`: Update the lm() analysis and then call `std_selected() again? (82ba713428375f1f421c64dfcc68c23c8b8d40b7)
- [x] `print()`: Update the output so users know it is a `std_selected` object, not an `lm` object. (ce0dc300cf89696f2411e43810d18ac2d9dd229a)

# No need to change
- `anova()`
- `hatvalues()`
- `formula()`
- `model.frame()`
- `model.matrix()`
- `nobs()`
- `plot()`
- `predict()`
- `residuals()`
- `rstandard()`
- `variable.names()`
- `drop1()`

# Do not change nor intercept the following
- `cooks.distance()`
- `dfbeta()`
- `dfbetas()`
- `influence()`
