### ISSUE TITLE
Fix package description

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#31]
# To-Do

- [X] Add citation to the manuscript. (ea44b195ea064d4e88f1bd12e75cd5ede3ad3fb1)
- [x] Update readme.md. (c549869cfdc06a0e7568c0fb19e0a4321178746e)
- [x] Add the link to the OSF page. (c549869cfdc06a0e7568c0fb19e0a4321178746e)
- [X] Check the fields to see if they meet CRAN requirements. (417c5d1d2697467684b61b7592b08aa2fa4ba1ac)
