### ISSUE TITLE
Final check before preparing the next major release

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#34]
Final checks before pushing to a new version

# To-Do

- [ ] Check the documentation of new functions.
- [ ] Check the documentation of old functions. Include named vectors in the documentation of affected functions.
- [ ] Proofread the vignettes.
- [ ] Update NEWS.
- [ ] Update DESCRIPTION.
- [ ] Test by `testthat`.
- [ ] Check by `devtools::check`.
