### ISSUE TITLE
Prepare precomputed results for vignettes

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#35]
# Note

- Building the vignettes take a long time due to bootstrapping.

# To-Do

- [x] Update `numerical_example_01.Rmd`. (2f9e9912795ae48b632c4a07bcece535cb2aea3e)
- [x] Update `numerical_example_02.Rmd`. (2f9e9912795ae48b632c4a07bcece535cb2aea3e)
- [x] Update `numerical_example_lavaan.Rmd.`. (2f9e9912795ae48b632c4a07bcece535cb2aea3e)
