### ISSUE TITLE
Final Check for Submission to CRAN

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#43]
Final checks before submission

# To-Do

- [x] Check the documentation of all functions. (75f6b480ce4417084650ad801dcc8c179699b207)
- [x] Proofread the vignettes. (5ae5a76604cef27176b2c633dac5cee5fd8913a4)
- [x] Update NEWS. (752e46b39a7f76e1f03a8dd1f022ee6b1792dcfd)
- [x] Update DESCRIPTION. (fb9dda438c814e44f0f81a7d477b7444a4d17532)
- [x] Test by `testthat`.
- [x] Check by `devtools::check`.
