### ISSUE TITLE
Final checks before submission

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#49]
Final checks before submission

# To-Do

- [x] Check the documentation of all functions.
- [x] Check the examples of all functions.
- [x] Proofread the vignettes.
- [x] Update NEWS.
- [x] Update DESCRIPTION.
- [x] Test by `testthat`.
- [x] Check by `devtools::check`.
