### ISSUE TITLE
`stdmod_lavaan()`: Add informative feedback

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#57]
# To-Do
- [x] Create a test dataset that will raise a warning if fitted by `sem`. (efa54076c6aed0f6de1213ac8280e579952c8c0c)
- [x] Write a test. (6ada2ca3a1cca6c83e27a1f48c3bfe8e7788187e)
- [x] Revise stdmod_lavaan to warn users of a fit with warning. (a2150b54fe86e2a024a582a6b11aa939022ee531)
- [x] Revise stdmod_lavaan to warn users of any failure in one or more bootstrap samples. (a2150b54fe86e2a024a582a6b11aa939022ee531)
- [x] Test the revised function.
