### ISSUE TITLE
Add t-based CI when standardization is not requested?

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#85]
# Note

For unstandardized conditional effects, t-based CIs are valid. Should consider reporting them.

Can be done by revising `cond_effect()` to store the CIs in `out_all`.

# To-Dos

- [x] Update the examples for `confint.cond_effect()`.
- [x] Add a test for `confint.cond_effect()`.
- [x] Update the examples for `coef.cond_effect()`.
- [x] Add a test for `coef.cond_effect()`.
- [x] Update the `print()` method to call the `confint()` and `coef()` methods.
- [x] Add a `confint()` method to `cond_effect`-class object. It can return either the OLS CIs or the bootstrap CIs.
- [x] Add a `coef()` method to `cond_effect`-class object.
