### ISSUE TITLE
Add R-square change for a moderation effect?

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/stdmod#86]
# To-Dos
- [x] Write a helper to find the highest order product term(s). (Can limit support for 2nd order terms for now.) <- Use `lmhelprs`
- [x] Write a helper to update a formula with a highest order product term removed. (Can limit support for 2nd order terms for now.)  <- Use `lmhelprs`
- [X] Write a helper to get the R-square when a highest order product term is removed (need to keep the lower order terms). (Can limit support for 2nd order terms for now.)  <- Use `lmhelprs`

# Status

Done in 0.2.9.1. Do not use lmhelprs() but adapted its function internally.

# Note

This is done in `summary.std_selected()`. The R-squared increase will be printed by the print method

Can use `lmhelprs::test_highest()`.

Need to think about where to report it, and what to report when a model has more than one product term.

Report it in the printout of `std_selected`-class objects?

Report it in the printout of `cond_effect`-class objects?
